# Generated by Django 4.0 on 2022-01-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='site_anme',
            new_name='site_name',
        ),
    ]
